import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy — ShipSafe',
  description: 'How ShipSafe collects, uses, and protects your personal data.',
};

const TOC = [
  { id: 'who-we-are', label: 'Who we are' },
  { id: 'what-shipsafe-does', label: 'What ShipSafe does' },
  { id: 'what-data-we-collect', label: 'What data we collect' },
  { id: 'why-we-collect', label: 'Why we collect this data' },
  { id: 'how-long', label: 'How long we keep your data' },
  { id: 'who-has-access', label: 'Who has access to your data' },
  { id: 'international-transfers', label: 'International data transfers' },
  { id: 'your-rights', label: 'Your rights' },
  { id: 'cookies', label: 'Cookies' },
  { id: 'security', label: 'Security' },
  { id: 'children', label: 'Children' },
  { id: 'data-breach', label: 'Data breach notification' },
  { id: 'changes', label: 'Changes to this policy' },
  { id: 'contact', label: 'Contact' },
];

const PROSE = [
  'prose prose-lg prose-invert prose-gray max-w-none',
  'prose-headings:scroll-mt-24',
  'prose-h2:mt-16 prose-h2:border-b prose-h2:border-gray-800/60 prose-h2:pb-4',
  'prose-h3:mt-10',
  'prose-p:leading-relaxed prose-p:text-gray-300',
  'prose-li:text-gray-300 prose-li:leading-relaxed',
  'prose-a:text-green-400 prose-a:no-underline hover:prose-a:underline',
  'prose-strong:text-white prose-strong:font-semibold',
  'prose-th:text-left prose-th:text-gray-400 prose-th:font-medium prose-th:py-3',
  'prose-td:py-3 prose-td:text-gray-300',
  'prose-table:text-base',
  'prose-code:text-green-400 prose-code:font-normal',
].join(' ');

export default function PrivacyPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-20 sm:px-8">
      <header className="mb-16">
        <h1 className="text-4xl font-bold tracking-tight sm:text-5xl">Privacy Policy</h1>
        <p className="mt-4 text-base text-gray-500">Last updated: February 12, 2026</p>
      </header>

      {/* Table of contents */}
      <nav className="mb-16 rounded-2xl border border-gray-800/60 bg-gray-900/40 px-7 py-6">
        <p className="mb-4 text-xs font-semibold text-gray-500 uppercase tracking-widest">Table of contents</p>
        <ol className="columns-2 gap-x-10 text-sm leading-8 text-gray-400">
          {TOC.map((item, i) => (
            <li key={item.id}>
              <a href={`#${item.id}`} className="transition-colors hover:text-green-400">
                {i + 1}. {item.label}
              </a>
            </li>
          ))}
        </ol>
      </nav>

      <div className={PROSE}>

        <h2 id="who-we-are">Who we are</h2>
        <p>
          ShipSafe is operated by [PRÉNOM NOM], self-employed worker (travailleur autonome) based in Montréal, Québec, Canada.
        </p>
        <p>
          <strong>Privacy Officer (Responsable de la protection des renseignements personnels):</strong><br />
          [PRÉNOM NOM]<br />
          Email: <a href="mailto:privacy@shipsafe.app">privacy@shipsafe.app</a>
        </p>

        <h2 id="what-shipsafe-does">What ShipSafe does</h2>
        <p>
          ShipSafe is an automated security audit tool for web applications. When you submit a URL, we perform publicly accessible security checks (HTTP requests, DNS lookups, TLS handshakes) — the same kind of checks any web browser performs. We do not access private data, user accounts, or databases of the applications we scan.
        </p>

        <h2 id="what-data-we-collect">What data we collect</h2>

        <h3>Account data</h3>
        <p>When you create an account:</p>
        <ul>
          <li><strong>Email address</strong> — to authenticate you and send you important notifications</li>
          <li><strong>Name</strong> (optional) — to personalize your experience</li>
        </ul>

        <h3>Scan data</h3>
        <p>When you run a scan:</p>
        <ul>
          <li><strong>URL submitted</strong> — to perform the security audit</li>
          <li><strong>Scan results</strong> — the security checks and score generated by our analysis</li>
        </ul>

        <h3>Payment data</h3>
        <p>When you subscribe to a paid plan:</p>
        <ul>
          <li><strong>Stripe Customer ID</strong> — to manage your subscription</li>
          <li>We do <strong>not</strong> store your credit card number, expiration date, or CVC. All payment processing is handled directly by Stripe.</li>
        </ul>

        <h3>Technical data</h3>
        <ul>
          <li><strong>IP address</strong> — for rate limiting and security. Retained for 30 days maximum.</li>
          <li><strong>Session cookies</strong> — strictly necessary for authentication. No tracking cookies are used.</li>
        </ul>

        <h2 id="why-we-collect">Why we collect this data (legal basis)</h2>
        <table>
          <thead>
            <tr><th>Data</th><th>Legal basis</th><th>Purpose</th></tr>
          </thead>
          <tbody>
            <tr><td>Email</td><td>Consent (account creation)</td><td>Authentication, service communications</td></tr>
            <tr><td>URL &amp; scan results</td><td>Contract performance</td><td>Delivering the service you requested</td></tr>
            <tr><td>Stripe Customer ID</td><td>Contract performance</td><td>Managing your subscription</td></tr>
            <tr><td>IP address</td><td>Legitimate interest</td><td>Security, rate limiting, abuse prevention</td></tr>
            <tr><td>Session cookies</td><td>Strictly necessary</td><td>Keeping you logged in</td></tr>
          </tbody>
        </table>

        <h2 id="how-long">How long we keep your data</h2>
        <table>
          <thead>
            <tr><th>Data</th><th>Retention period</th></tr>
          </thead>
          <tbody>
            <tr><td>Account data</td><td>Duration of your account + 30 days after deletion</td></tr>
            <tr><td>Scan results (authenticated)</td><td>Duration of your account</td></tr>
            <tr><td>Scan results (anonymous)</td><td>90 days</td></tr>
            <tr><td>IP addresses</td><td>30 days</td></tr>
            <tr><td>Payment records</td><td>Duration of your account + 6 years (tax obligations)</td></tr>
          </tbody>
        </table>

        <h2 id="who-has-access">Who has access to your data</h2>
        <p>We use the following service providers (sub-processors):</p>
        <table>
          <thead>
            <tr><th>Provider</th><th>Purpose</th><th>Location</th><th>Safeguards</th></tr>
          </thead>
          <tbody>
            <tr><td>Stripe</td><td>Payment processing</td><td>USA / EU</td><td>SOC 2 certified, SCCs</td></tr>
            <tr><td>Resend</td><td>Transactional emails</td><td>USA</td><td>DPA available</td></tr>
            <tr><td>[HÉBERGEUR]</td><td>Hosting</td><td>[LOCALISATION]</td><td>[GARANTIES]</td></tr>
          </tbody>
        </table>
        <p>We do not sell, rent, or share your personal data with third parties for marketing purposes.</p>

        <h2 id="international-transfers">International data transfers</h2>
        <p>
          Your data may be processed in countries outside Canada or the European Union (notably the United States) through our service providers. These transfers are protected by Standard Contractual Clauses (SCCs) approved by the European Commission and adequate safeguards as required by Canadian privacy law.
        </p>

        <h2 id="your-rights">Your rights</h2>

        <h3>If you are in the European Union (GDPR)</h3>
        <p>You have the right to:</p>
        <ul>
          <li><strong>Access</strong> your personal data</li>
          <li><strong>Rectify</strong> inaccurate data</li>
          <li><strong>Delete</strong> your data (&quot;right to be forgotten&quot;)</li>
          <li><strong>Port</strong> your data to another service</li>
          <li><strong>Object</strong> to processing based on legitimate interest</li>
          <li><strong>Withdraw</strong> consent at any time</li>
          <li><strong>Lodge a complaint</strong> with your local data protection authority</li>
        </ul>

        <h3>If you are in Québec or Canada (Loi 25 / LPRPDE)</h3>
        <p>You have the right to:</p>
        <ul>
          <li><strong>Access</strong> your personal data</li>
          <li><strong>Rectify</strong> inaccurate data</li>
          <li><strong>Withdraw</strong> your consent</li>
          <li><strong>Request deletion</strong> of your data</li>
          <li><strong>Request de-indexing</strong> of your data</li>
          <li><strong>Data portability</strong> in a commonly used technological format</li>
          <li><strong>Lodge a complaint</strong> with the Commission d&apos;accès à l&apos;information du Québec</li>
        </ul>

        <h3>How to exercise your rights</h3>
        <p>
          Send your request to: <a href="mailto:privacy@shipsafe.app">privacy@shipsafe.app</a>
        </p>
        <p>
          We will respond within 30 days. We may ask you to verify your identity before processing your request.
        </p>

        <h3>Account deletion</h3>
        <p>
          You can delete your account at any time from your account settings. This will permanently delete all your personal data, scan history, and reports within 30 days. Payment records will be retained for 6 years as required by tax law.
        </p>

        <h2 id="cookies">Cookies</h2>
        <p>
          ShipSafe uses only <strong>strictly necessary cookies</strong> for authentication (session management). We do not use analytics cookies, advertising cookies, or tracking technologies.
        </p>
        <p>
          Since we only use strictly necessary cookies, no consent banner is required under GDPR (Article 5.3 of the ePrivacy Directive) or Loi 25.
        </p>
        <p>
          If we add non-essential cookies in the future, we will update this policy and implement a consent mechanism before deploying them.
        </p>
        <p>
          For more details, see our <a href="/cookies">Cookie Policy</a>.
        </p>

        <h2 id="security">Security</h2>
        <p>We take reasonable measures to protect your data:</p>
        <ul>
          <li>All communications are encrypted via HTTPS/TLS</li>
          <li>Database access is restricted to internal network only</li>
          <li>Authentication uses secure, encrypted sessions</li>
          <li>Payment data is handled exclusively by Stripe (PCI DSS compliant)</li>
        </ul>

        <h2 id="children">Children</h2>
        <p>
          ShipSafe is not directed at children under 16. We do not knowingly collect personal data from children. If you believe a child has provided us with personal data, please contact us at <a href="mailto:privacy@shipsafe.app">privacy@shipsafe.app</a>.
        </p>

        <h2 id="data-breach">Data breach notification</h2>
        <p>In the event of a security incident involving your personal data, we will:</p>
        <ul>
          <li>Notify the Commission d&apos;accès à l&apos;information du Québec (as required by Loi 25)</li>
          <li>Notify affected users without undue delay</li>
          <li>Notify relevant EU supervisory authorities within 72 hours if required by GDPR</li>
        </ul>

        <h2 id="changes">Changes to this policy</h2>
        <p>
          We may update this policy from time to time. We will notify you of significant changes by email or by a notice on our website. Your continued use of ShipSafe after changes constitutes acceptance of the updated policy.
        </p>

        <h2 id="contact">Contact</h2>
        <p>
          For any questions about this privacy policy or your personal data:
        </p>
        <p>
          [PRÉNOM NOM]<br />
          Email: <a href="mailto:privacy@shipsafe.app">privacy@shipsafe.app</a><br />
          Location: Montréal, Québec, Canada
        </p>
      </div>
    </main>
  );
}
